Added Terraform Workflow
rhdhorchestrator/serverless-workflow-examples pull request #54
Opened 2024-12-31 09:53 UTC by ElaiShalevRH

This Workflow is a PoC of allowing to run Terraform workloads from within Orchestrator. Each workflow run can run a single Terraform plan and apply it. 
This PR adds a new workflow, some terraform open-api spec, and a custom Java class to handle some of the workflow logic.

2025-01-02 08:47 UTC, masayag commented on terraform/src/main/resources/README.md
> +# terraform
pls pull this file to the top level of the workflow, it will be easier to find and use.

2025-01-02 10:00 UTC, gabriel-farache reviewed
Few comments, I will try to run the workflow and I'll let you know

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +
remove the newline pls

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +
remove the newline here too

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +
remove the newline here too

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +            URL targetUrl = uri.toURL();
you could do 
```
 URL targetUrl = new URI(targetUri).toURL();
```
or even
```
URL targetUrl = new URL(targetUri);
```
but not sure why the name is `targetURI` and not `targetURL`, is there a difference?

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +            HttpResponse<InputStream> response = client.send(request, HttpResponse.BodyHandlers.ofInputStream()); // not
what does the commend mean? `// not`

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/resources/terraform-job.sw.yaml
> +          refName: HandleTerraformConfigUpload
you don't manage the value returned by the java custom code, you should do it by adding
```
actionDataFilter:
          toStateData: ".responseCode"
```

and then create a new state that evaluates it

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +                e.printStackTrace();
maybe instead of returning an int, you could return an object with the response code integer and an error string.

The response code will be the HTTP response code and the error string will only be populated when there is an exception and should contain its message or at least a message indicating where it fails so it can be shared to the user

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/resources/terraform-job.sw.yaml
> +          toStateData: .extractedURL
where is this used?

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/resources/terraform-job.sw.yaml
> +            targetUri: .configurationVersions.data.attributes."upload-url"
the name is `upload-url` in the `configurationVersions` object, why name it `targetUri` and not `targetURL`?

Should `extractURL` be used here? (and renamed because it's quite vague)

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/resources/terraform-job.sw.yaml
> +          arguments:
What source and target?
Maybe `sourceUrl` could be renamed `tarArchiveSourceURL` so it's obvious what it is
Same with `targetUri` that may be renamed to `uploadURL` instead

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/resources/README.md
> +1. Set up a Terraform Cloud instance with a Project, a Workspace, and procure a WorkspaceID.
maybe worth to put the tutorial links here too

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/resources/README.md
> +3. Make sure to configure any Terraform Providers Credentials on the Terraform instance.
Same as above, maybe worth to put some link describing how to do it

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/resources/terraform-job.sw.yaml
> +
remove this new line pls

2025-01-02 10:00 UTC, gabriel-farache commented on terraform/src/main/resources/terraform-job.sw.yaml
> +              description: '"Terraform job workflow id: " + $WORKFLOW.instanceId " has failed to provision the Terraform configurations."'
may be nice to put the `.terraformRun.data.attributes.status` status here too

2025-01-02 11:24 UTC, ElaiShalevRH commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +            HttpResponse<InputStream> response = client.send(request, HttpResponse.BodyHandlers.ofInputStream()); // not
leftover, will delete

2025-01-02 11:38 UTC, ElaiShalevRH commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +                e.printStackTrace();
Sounds good, 
what should this object be? a JSON string? or a map?

2025-01-02 11:41 UTC, ElaiShalevRH commented on terraform/src/main/resources/terraform-job.sw.yaml
> +          toStateData: .extractedURL
it is not anymore, will remove.

2025-01-02 11:42 UTC, ElaiShalevRH commented on terraform/src/main/resources/terraform-job.sw.yaml
> +            targetUri: .configurationVersions.data.attributes."upload-url"
I'll change the whole naming schema of these variables

2025-01-02 12:37 UTC, ElaiShalevRH commented on terraform/src/main/resources/terraform-job.sw.yaml
> +          arguments:
the extract method was needed whan I tried to upload using a custom open-api spec. Now that I moved to Java HTTP handler, there is no need for extraction

2025-01-02 12:44 UTC, ElaiShalevRH commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +            URL targetUrl = uri.toURL();
casting string to URL is deprecated, and is recommended to use the URI method, apparently

2025-01-02 14:02 UTC, gabriel-farache commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +            URL targetUrl = uri.toURL();
oki doki

2025-01-02 14:04 UTC, gabriel-farache commented on terraform/src/main/java/io/janus/workflow/terraform/HandleTerraformConfigUpload.java
> +                e.printStackTrace();
a POJO, it will be converted to JSON I think
See what is done for the advanced template (https://github.com/rhdhorchestrator/workflow-software-templates/blob/main/scaffolder-templates/skeletons/advanced-workflow-skeleton/src/main/java/%24%7B%7Bvalues.groupId%7D%7D/%24%7B%7Bvalues.artifactId%7D%7D/SampleAssessment.java)

2025-01-03 13:41 UTC, gabriel-farache commented on terraform/pom.xml
> +        <maven.compiler.release>21</maven.compiler.release>
Needs to be set to 17 like the others maven.compiler target https://github.com/rhdhorchestrator/serverless-workflow-examples/pull/54/files#diff-d0cee909802d5c3fe8609a1d603d52363edef9af5be3496227ee87607a6dd222R15-R16

2025-01-03 13:42 UTC, gabriel-farache commented on terraform/pom.xml
> +    </properties>
I had to add
```
<repositories>
    <repository>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>redhat</id>
      <url>https://maven.repository.redhat.com/ga</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>redhat</id>
      <url>https://maven.repository.redhat.com/ga</url>
    </pluginRepository>
  </pluginRepositories>
```
for `mvn quarkus:dev` to work

2025-01-03 13:43 UTC, gabriel-farache commented on terraform/src/main/docker/Dockerfile.jvm
> +# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/aap-db-deploy-jvm .
copy/pasta gone wrong, either remove the comment or set the correct value for the workflow name :)

2025-01-03 14:06 UTC, gabriel-farache requested changes

2025-01-03 14:06 UTC, gabriel-farache commented on terraform/src/main/resources/README.md
> +| `TERRAFORM_TOKEN`      | The Access Token for Terraform Cloud | ✅ |
According https://developer.hashicorp.com/terraform/cloud-docs/api-docs/configuration-versions, the API token must be a [user token](https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/users#api-tokens) or [team token](https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens#team-api-tokens). Please put that (important) information in the README

2025-01-03 14:17 UTC, gabriel-farache commented on terraform/src/main/resources/terraform-job.sw.yaml
> +    dataConditions:
You are missing at least 1 condition:
```
{
   "data":{
      "id":"run-Xv5zwzmBBDLg3geR",
      "type":"runs",
      "attributes":{
         "actions":{
            "is-cancelable":false,
            "is-confirmable":false,
            "is-discardable":false,
            "is-force-cancelable":false
         },
         "allow-config-generation":true,
         "allow-empty-apply":false,
         "auto-apply":false,
         "canceled-at":null,
         "created-at":"2025-01-03T14:03:43.974Z",
         "has-changes":false,
         "is-destroy":false,
         "message":"Triggered via API",
         "plan-only":false,
         "refresh":true,
         "refresh-only":false,
         "replace-addrs":null,
         "save-plan":false,
         "source":"tfe-configuration-version",
         "status-timestamps":{
            "errored-at":"2025-01-03T14:09:18+00:00",
            "queuing-at":"2025-01-03T14:03:44+00:00",
            "planning-at":"2025-01-03T14:03:45+00:00",
            "plan-queued-at":"2025-01-03T14:03:44+00:00",
            "plan-queueable-at":"2025-01-03T14:03:43+00:00"
         },
         "status":"errored",
         "target-addrs":null,
         "trigger-reason":"manual",
         "terraform-version":"1.10.3",
         "updated-at":"2025-01-03T14:09:18.621Z",
         "permissions":{
            "can-apply":true,
            "can-cancel":true,
            "can-comment":true,
            "can-discard":true,
            "can-force-execute":true,
            "can-force-cancel":true,
            "can-override-policy-check":true
         },
         "variables":[
            
         ]
      },
...
```
When the execution failed, the workflow keep running

2025-01-06 13:44 UTC, gabriel-farache commented on terraform/src/main/resources/terraform-job.sw.yaml
> +      - condition: (.returnObject.errorMessage == "")
why not check the response code instead?

2025-01-06 13:46 UTC, gabriel-farache commented on terraform/src/main/resources/terraform-job.sw.yaml
> +              entityRef: ["user:default/guest"]
in other worfklows we have a recipients input which is then used here
Should we do the same here or do we consider it's OK for example?

2025-01-06 13:46 UTC, gabriel-farache reviewed
2 non-blocking questions
Tested locally and it works

2025-01-06 14:13 UTC, ElaiShalevRH commented on terraform/src/main/resources/terraform-job.sw.yaml
> +      - condition: (.returnObject.errorMessage == "")
There could be many response codes (200, 400, 401, 403 etc).  200 OK is the only case when the error will be null.

2025-01-06 14:13 UTC, ElaiShalevRH commented on terraform/src/main/resources/terraform-job.sw.yaml
> +              entityRef: ["user:default/guest"]
Yeah we can do that here too, I'll try that

2025-01-06 14:16 UTC, gabriel-farache commented on terraform/src/main/resources/terraform-job.sw.yaml
> +      - condition: (.returnObject.errorMessage == "")
why not test if the response code is 20x then? (>= 200 and < 300 for instance)

2025-01-07 07:48 UTC, gabriel-farache approved these changes

2025-01-07 08:25 UTC, masayag commented on terraform/README.md
> +
Can you add also the svg file (workflow's diagram) and include it in this README.md file?

2025-01-07 11:17 UTC, masayag approved these changes

2025-01-07 11:17 UTC, merged